### ISSUE TITLE
Plugin install doesn't work

### ISSUE THREAD

**Issue by devlynhw** [arongergely/qgis-h3-toolkit-plugin#10]
I have used the H3 toolkit on my old laptop and am setting up my new one.

Installed QGIS 3.34.0. 

It looks like H3 is installed: 

PS C:\Users\"me"> py -m pip install h3
Requirement already satisfied: h3 in c:\users\"me"\appdata\local\programs\python\python312\lib\site-packages (3.7.6)

When I try and install the plugin, the manager says the install is successful but the toolbar doesn't display and I get an error message on the scroll bar at the top of the map:
![image](https://github.com/arongergely/qgis-h3-toolkit-plugin/assets/151692108/24e1b67c-4d4a-4363-bc21-96b89673813d)
![image](https://github.com/arongergely/qgis-h3-toolkit-plugin/assets/151692108/22120cde-3ffb-43ac-a01e-450636be7d38)

Where have I gone wrong?

**Comment by arongergely** [comment]
You probably installed h3 to the wrong python environment.
QGIS comes with its own python on Windows, so you would need to find a way to install its env.

How to do that depends on how you installed QGIS: OSGeo4W or the standalone installer.
The former better as I understand - makes it easier to install python packages. More info here; https://gis.stackexchange.com/questions/141320/installing-3rd-party-python-libraries-for-qgis-on-windows


But first try this:
Open a python console in your current QGIS by pressing Ctrl+Alt+P or by clicking this button on the GUI: 
![image](https://github.com/arongergely/qgis-h3-toolkit-plugin/assets/7316393/d6ba7dde-4167-43fe-a944-52298a9471b5)

Then run this command: 
```shell
!pip install 'h3<=3.99'
```
If this does not work then re-install QGIS via the OSgeo4W and use the above StackExchange to install the missing package.

Good luck!

**Comment by devlynhw** [comment]
Not a stupid question, I'm a stupid user :)
They are there! Thank you
