### ISSUE TITLE
AttributeError: module 'h3' has no attribute 'polyfill'

### ISSUE THREAD

**Issue by michaelosunga** [arongergely/qgis-h3-toolkit-plugin#15]
Using QGIS, I am trying to generate H3 grids inside my polygon at a resolution of 7 but I keep geting an error that says _Traceback (most recent call last):
File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\h3_toolkit\processing\algorithms.py", line 254, in processAlgorithm
newSet = h3.polyfill(geoJsonDict, resolution, geo_json_conformant=True)
^^^^^^^^^^^
AttributeError: module 'h3' has no attribute 'polyfill'

Execution failed after 0.03 seconds_

Not too sure what the issue could be

**Comment by michaelosunga** [comment]
![Screenshot 2024-11-09 012844](https://github.com/user-attachments/assets/1aa8e841-36de-4a50-9548-b015cc191841)
Here is the screenshot

**Comment by arongergely** [comment]
What is you h3 library version? you can check it via python or through the plugin:
Go to Plugins menu in QGIS -> H3 Toolkit Plugin -> About.
It should print the h3 core and python binding versions.

The plugin only supports v3.x  for now.

**Comment by michaelosunga** [comment]
Many thanks for your quick response. I am using version 4.1 of the h3 library as shown in the screenshot
![Screenshot 2024-11-09 084041](https://github.com/user-attachments/assets/a41ab60a-674e-4581-b358-cce6ceb14065)

**Comment by arongergely** [comment]
I see, h3 v4.x is not supported. You would need to downgrade to v3.x for the plugin to work.

**Comment by michaelosunga** [comment]
![h3 versions 3 7 7](https://github.com/user-attachments/assets/30ea62cd-498c-450e-b6fd-71429d0134e3). [](url). Hello Aron. I did install h3 version 3.7.7 and everything seems to work. Thank you so much for your assistance

**Comment by michaelosunga** [comment]
Resolved
